## YAML Template.
parser: jp.co.chooyan.commander.plugin.parse.SimpleCommandParser
analyzer: jp.co.chooyan.commander.plugin.analyze.HistoryCountAnalyzer
outputter: jp.co.chooyan.commander.plugin.output.JsonOutputter